version: '3.7'

services:
  mongo:
    image: mvertes/alpine-mongo
    container_name: mongo
    ports:
      - '27017:27017'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
